packages:
  - 'encv-mobile'
  - 'encv-mobile/plugin-openlist/web'
  - 'encv-mobile/plugin-mpv-player/web'
  - 'encv-mobile/plugin-simverse/web'
  - 'simverse-frontend'
  - 'preview-gateway'
  - 'packages/*'
allowBuilds:
  core-js: false
  cypress: false
  esbuild: false
