#!/usr/bin/env bash
# 沙箱 kotlinc 一键准备脚本
#
# Why:
#   每次新沙箱会话 /tmp 都被清空，kotlin 编译器需要重新准备。
#   手动 curl 4 个 jar + 写 wrapper 易错（漏 jar / 错版本 / 漏 chmod），
#   而且后续 AI 会话不知道有现成 wrapper，必须重做。
#
# What:
#   1. 从 libs.versions.toml 自动读 kotlin 版本（不硬编码）
#   2. 从 Maven Central 拉 4 个 jar（compiler-embeddable + stdlib + reflect + coroutines）
#   3. 写 /usr/local/bin/kotlinc-<version> 包装脚本（java -cp ... K2JVMCompiler）
#   4. 跑 `kotlinc-<version> -version` 验证可用
#   5. 打印就绪报告 + 用法 + 退出码
#
# 设计参考: app/encv-mobile/scripts/start-preview.sh
#   - set -euo pipefail + 严格错误处理
#   - step() 函数统一步骤输出
#   - 状态报告 cat <<EOF 收尾
#   - 6 步骤结构
#
# 退出码:
#   0 = 成功（wrapper 就绪）
#   1 = 缺少前置依赖（java 不在 PATH / libs.versions.toml 不存在 / 无 kotlin 版本声明）
#   2 = 网络拉取失败（沙箱到 Maven Central 不通）
#   3 = 版本校验失败（wrapper 启动异常）
#
# 用法:
#   bash /workspace/.trae/scripts/setup-kotlinc.sh
#
# 清理（如需重做）:
#   rm -rf /tmp/kotlin-home /usr/local/bin/kotlinc-*
set -euo pipefail

# ---- 路径定位 ----
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# 兼容 .trae/scripts/ 和 .trae/ 平铺两种放法
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." 2>/dev/null && pwd)"

# ---- 工具函数 ----
step() { echo ""; echo "==> $*"; }
fail() { echo "❌ $*" >&2; exit "${2:-1}"; }

# ---- 找 libs.versions.toml（monorepo 兼容）----
find_versions_toml() {
    local candidates=(
        "${REPO_ROOT}/app/encv-mobile/android/gradle/libs.versions.toml"
        "${REPO_ROOT}/android/gradle/libs.versions.toml"
        "${REPO_ROOT}/gradle/libs.versions.toml"
        "${REPO_ROOT}/libs.versions.toml"
    )
    local f
    for f in "${candidates[@]}"; do
        [[ -f "$f" ]] && { echo "$f"; return 0; }
    done
    return 1
}

# ---- Step 0: 前置检查 ----
step "0/6 前置检查（java / curl / libs.versions.toml）"

command -v java >/dev/null 2>&1 || fail "java 不在 PATH（沙箱应通过 mise 装好）" 1
command -v curl >/dev/null 2>&1 || fail "curl 不在 PATH" 1

VERSIONS_TOML="$(find_versions_toml)" || fail "未找到 libs.versions.toml（搜索路径: app/encv-mobile/android/gradle/）" 1
echo "    libs.versions.toml: ${VERSIONS_TOML}"

# 解析 kotlin = "X.Y.Z"  (用 || true 防止 set -e 误触)
KOTLIN_VERSION="$(grep -E '^kotlin\s*=' "${VERSIONS_TOML}" | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true)"
[[ -n "${KOTLIN_VERSION:-}" ]] || fail "libs.versions.toml 中无 kotlin 版本声明" 1
echo "    Kotlin version: ${KOTLIN_VERSION}"

# ---- Step 1: 创建 KOTLIN_HOME ----
step "1/6 创建 KOTLIN_HOME=/tmp/kotlin-home/lib"
KOTLIN_HOME="/tmp/kotlin-home"
mkdir -p "${KOTLIN_HOME}/lib"
echo "    ${KOTLIN_HOME}/lib/ 就绪"

# ---- Step 2: 从 Maven Central 拉 4 个 jar ----
step "2/6 从 Maven Central 拉 4 个 jar（每个 --max-time 60s, curl -f 失败立即 abort）"

MAVEN_BASE="https://repo1.maven.org/maven2"

# 幂等：已有且 size 合理就 skip
download_jar() {
    local group_path="$1"   # 例: org/jetbrains/kotlin
    local artifact="$2"     # 例: kotlin-stdlib
    local version="$3"      # 例: 2.3.21
    local out="${KOTLIN_HOME}/lib/${artifact}-${version}.jar"

    if [[ -s "$out" ]]; then
        local size
        size="$(stat -c%s "$out" 2>/dev/null || echo 0)"
        # kotlin-compiler-embeddable 至少 50MB，其余至少 100KB
        local min_size=100000
        [[ "$artifact" == "kotlin-compiler-embeddable" ]] && min_size=50000000
        if [[ "$size" -ge "$min_size" ]]; then
            echo "    [skip] ${artifact}-${version}.jar 已有 (${size} bytes)"
            return 0
        fi
        echo "    [warn] ${artifact}-${version}.jar 存在但 size=${size} < ${min_size}, 重新拉"
        rm -f "$out"
    fi

    local url="${MAVEN_BASE}/${group_path}/${artifact}/${version}/${artifact}-${version}.jar"
    echo "    [get ] ${url}"
    if ! curl -sL --max-time 60 -f -o "$out" "$url"; then
        rm -f "$out"
        fail "下载失败: ${url}（沙箱到 Maven Central 是否可达? curl 测试: curl -I ${url}）" 2
    fi
    local size
    size="$(stat -c%s "$out" 2>/dev/null || echo 0)"
    echo "    [done] ${artifact}-${version}.jar  ${size} bytes"
}

# 4 个 jar（顺序敏感：compiler-embeddable 第一个，最容易失败）
download_jar "org/jetbrains/kotlin"  "kotlin-compiler-embeddable" "${KOTLIN_VERSION}"
download_jar "org/jetbrains/kotlin"  "kotlin-stdlib"              "${KOTLIN_VERSION}"
download_jar "org/jetbrains/kotlin"  "kotlin-reflect"             "${KOTLIN_VERSION}"
# coroutines 不与 KOTLIN_VERSION 强绑定，用稳定版 1.10.2
download_jar "org/jetbrains/kotlinx" "kotlinx-coroutines-core-jvm" "1.10.2"

# ---- Step 3: 写 /usr/local/bin/kotlinc-<version> 包装脚本 ----
step "3/6 写 /usr/local/bin/kotlinc-${KOTLIN_VERSION} 包装脚本"

WRAPPER="/usr/local/bin/kotlinc-${KOTLIN_VERSION}"
# 用 'EOF' 禁止 shell 展开，直接把占位符写进去再 sed 替换
cat > "${WRAPPER}" <<'WRAPPER_EOF'
#!/bin/bash
# Auto-generated by /workspace/.trae/scripts/setup-kotlinc.sh
# 用法: kotlinc-__VERSION__ [options] <source files>
# 维护: 任何后续 AI 改 kotlin 版本时，重新跑 setup-kotlinc.sh 即可（不需手改本文件）
KOTLIN_HOME="__KOTLIN_HOME__"
exec java -cp \
    "$KOTLIN_HOME/lib/kotlin-compiler-embeddable-__VERSION__.jar:$KOTLIN_HOME/lib/kotlin-stdlib-__VERSION__.jar:$KOTLIN_HOME/lib/kotlin-reflect-__VERSION__.jar:$KOTLIN_HOME/lib/kotlinx-coroutines-core-jvm-1.10.2.jar" \
    org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
    -kotlin-home "$KOTLIN_HOME" \
    "$@"
WRAPPER_EOF

# 替换占位符（不用 sed 也不复杂，直接用 here-doc + 变量展开更安全）
# 因为上面用了 'EOF'，占位符未被展开，这里 sed 替换
sed -i \
    -e "s|__KOTLIN_HOME__|${KOTLIN_HOME}|g" \
    -e "s|__VERSION__|${KOTLIN_VERSION}|g" \
    "${WRAPPER}"
chmod +x "${WRAPPER}"
echo "    ${WRAPPER} 已 chmod +x"

# ---- Step 4: 验证 ----
step "4/6 验证 kotlinc-${KOTLIN_VERSION} -version"

if ! "${WRAPPER}" -version 2>&1 | head -10; then
    fail "kotlinc 启动失败（缺 jar / java 版本不对 / classpath 写错）" 3
fi

# ---- Step 5: 状态报告 ----
step "5/6 ✅ Kotlin 编译器就绪"
cat <<EOF

========================================
✅ 沙箱 Kotlin 调试环境已就绪

  Kotlin 版本:    ${KOTLIN_VERSION}
  KOTLIN_HOME:    ${KOTLIN_HOME}
  Wrapper:        ${WRAPPER}
  4 个 jar 位置:
    - ${KOTLIN_HOME}/lib/kotlin-compiler-embeddable-${KOTLIN_VERSION}.jar
    - ${KOTLIN_HOME}/lib/kotlin-stdlib-${KOTLIN_VERSION}.jar
    - ${KOTLIN_HOME}/lib/kotlin-reflect-${KOTLIN_VERSION}.jar
    - ${KOTLIN_HOME}/lib/kotlinx-coroutines-core-jvm-1.10.2.jar

  快速自检（推荐每个 AI 会话开始时跑一次）:
    ${WRAPPER} -version

  用法示例（语法检查，不依赖 android.jar/compose.jar）:
    cd /workspace/app/encv-mobile/plugin-openlist
    ${WRAPPER} -no-stdlib -no-reflect -Xsuppress-version-warnings \\
        src/main/java/com/encvgo/plugin/openlist/*.kt -d /tmp/out 2>/tmp/err.log

    # 过滤"真 bug"（syntax / 抽象成员 / Composable 上下文）
    grep -E "Syntax error|abstract member|Composable invocations|Unclosed comment" /tmp/err.log

    # unresolved reference 是预期的（沙箱无 android.jar / combolite-core.jar）
    grep -c "unresolved reference" /tmp/err.log

  沙箱特性（必读）:
    - /tmp 在新会话清空，每次都需重跑本脚本
    - jar 全部走 Maven Central,绝不会走 GitHub Releases / Google CDN / JetBrains CDN
    - 沙箱无 android.jar / compose.jar / combolite-core.jar,只能抓 parse/syntax 错
      → unresolved reference 数字大但都是预期的,真伪需 CI 跑全量

  清理（如需重做）:
    rm -rf ${KOTLIN_HOME} ${WRAPPER}
========================================
EOF

step "6/6 退出码 0（环境就绪，可开始 Kotlin 调试）"
exit 0
