#!/usr/bin/env node
/**
 * codemogger css-source — trace a compiled CSS *product* back to its SCSS source.
 *
 * Sass (and Vite's sass pipeline) emit a `*.css.map` source map alongside every
 * compiled CSS file. That map is the canonical, lossless bridge from a generated
 * CSS rule back to the exact `.scss` partial + line that produced it — even when
 * the rule was generated by a `@mixin` / `@function` / `@each` loop (where the
 * selector/text never appears literally in the SCSS). This tool decodes that map
 * (base64-VLQ) and answers: "which SCSS file/line produced CSS line N?"
 *
 * Usage:
 *   node css-source.mjs <compiled.css> [--line N] [--json] [--summary] [--top N]
 *
 * Modes:
 *   (default, no --line)  per-source summary: how many generated CSS lines came
 *                         from each .scss source, and a few sample line mappings.
 *   --line N (1-based)    show the SCSS provenance of one CSS line (file:line:col
 *                         + the originating SCSS snippet).
 *   --json                machine-readable output (for scripting / MCP).
 *
 * Source-map discovery:
 *   1. `/*# sourceMappingURL=... *\/` (or `//# ...`) in the CSS — supports both a
 *      sibling path and an inline `data:` URI.
 *   2. else a sibling `<name>.css.map` next to the CSS file.
 *
 * No third-party deps — pure Node (fs / path / url) + a hand-rolled VLQ decoder.
 */

import { readFileSync, existsSync, readFileSync as readFile } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

// --- base64-VLQ decoder (source map mappings field) -------------------------
const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const B64VAL = new Map([...B64].map((c, i) => [c, i]));

function decodeVLQ(str) {
  const out = [];
  let i = 0;
  let shift = 0;
  let value = 0;
  while (i < str.length) {
    const c = str[i++];
    const v = B64VAL.get(c);
    if (v === undefined) throw new Error(`bad base64 char in VLQ: ${JSON.stringify(c)}`);
    const cont = v & 32;
    value += (v & 31) << shift;
    shift += 5;
    if (!cont) {
      const signed = value & 1 ? -(value >> 1) : value >> 1;
      out.push(signed);
      value = 0;
      shift = 0;
    }
  }
  return out;
}

// --- CLI args ---------------------------------------------------------------
const argv = process.argv.slice(2);
let cssFile = null;
let lineNo = null;
let asJson = false;
let asSummary = false;
let topN = 8;
const positional = [];
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--json") asJson = true;
  else if (a === "--summary") asSummary = true;
  else if (a === "--line") lineNo = Number(argv[++i]);
  else if (a === "--top") topN = Number(argv[++i]);
  else if (a.startsWith("--line=")) lineNo = Number(a.slice("--line=".length));
  else if (a.startsWith("--top=")) topN = Number(a.slice("--top=".length));
  else positional.push(a);
}
if (positional.length) cssFile = positional[0];

if (!cssFile) {
  process.stderr.write(
    "usage: node css-source.mjs <compiled.css> [--line N] [--json] [--summary] [--top N]\n",
  );
  process.exit(2);
}
cssFile = path.resolve(cssFile);
if (!existsSync(cssFile)) {
  process.stderr.write(`css-source: file not found: ${cssFile}\n`);
  process.exit(1);
}

// --- locate + load the source map ------------------------------------------
function findSourceMap(cssPath) {
  const raw = readFileSync(cssPath, "utf8");
  const m = raw.match(/[#@]\s*sourceMappingURL=(.+?)\s*$/m);
  if (m) {
    let url = m[1].trim();
    if (url.startsWith("data:")) {
      const comma = url.indexOf(",");
      const meta = url.slice(5, comma);
      const payload = url.slice(comma + 1);
      const b64 = meta.endsWith(";base64") ? payload : Buffer.from(payload, "utf8").toString("base64");
      return { map: JSON.parse(Buffer.from(b64, "base64").toString("utf8")), origin: "inline data URI" };
    }
    const p = path.resolve(path.dirname(cssPath), url);
    if (existsSync(p)) return { map: JSON.parse(readFileSync(p, "utf8")), origin: p };
  }
  const sibling = cssPath.replace(/\.css$/, ".css.map");
  if (existsSync(sibling)) return { map: JSON.parse(readFileSync(sibling, "utf8")), origin: sibling };
  return { map: null, origin: null };
}

const { map, origin } = findSourceMap(cssFile);
if (!map) {
  process.stderr.write(
    `css-source: no source map found for ${cssFile}\n` +
      `  (looked for /*# sourceMappingURL= */ and a sibling <name>.css.map)\n` +
      `  Recompile the SCSS with source maps enabled (sass --source-map, or\n` +
      `   vite build with css.preprocessorOptions.scss.sourceMap + build.cssSourcemap).\n`,
  );
  process.exit(1);
}

const sources = map.sources || [];
const sourcesContent = map.sourcesContent || [];
const sourceRoot = map.sourceRoot || "";
const cssDir = path.dirname(cssFile);

function resolveSource(idx) {
  let s = sources[idx] || "";
  if (!s) return null;
  if (s.startsWith("file://")) return fileURLToPath(s);
  if (sourceRoot && !path.isAbsolute(s) && !s.startsWith(".")) s = path.join(sourceRoot, s);
  if (path.isAbsolute(s)) return s;
  return path.resolve(cssDir, s);
}

function snippetFor(idx, origLine /* 0-based */) {
  let text = null;
  if (sourcesContent[idx] != null) {
    const lines = sourcesContent[idx].split("\n");
    text = lines[origLine] ?? "";
  } else {
    const p = resolveSource(idx);
    if (p && existsSync(p)) {
      const lines = readFileSync(p, "utf8").split("\n");
      text = lines[origLine] ?? "";
    }
  }
  return (text || "").replace(/\s+$/, "");
}

// --- decode mappings --------------------------------------------------------
const decoded = []; // decoded[genLine] = [{genCol, src?, origLine?, origCol?, name?}]
let prevSrc = 0;
let prevOrigLine = 0;
let prevOrigCol = 0;
let prevName = 0;
const mapLines = (map.mappings || "").split(";");
mapLines.forEach((line, genLine) => {
  let genCol = 0;
  const segs = [];
  if (line.length) {
    for (const seg of line.split(",")) {
      if (!seg) continue;
      const f = decodeVLQ(seg);
      genCol += f[0];
      const entry = { genCol };
      if (f.length >= 4) {
        prevSrc += f[1];
        prevOrigLine += f[2];
        prevOrigCol += f[3];
        entry.src = prevSrc;
        entry.origLine = prevOrigLine;
        entry.origCol = prevOrigCol;
        if (f.length >= 5) {
          prevName += f[4];
          entry.name = prevName;
        }
      }
      segs.push(entry);
    }
  }
  decoded.push(segs);
});

function srcLabel(idx) {
  const p = resolveSource(idx);
  if (!p) return sources[idx] || `source#${idx}`;
  // show path relative to cwd when possible for readability
  try {
    return path.relative(process.cwd(), p) || p;
  } catch {
    return p;
  }
}

// --- mode: single line ------------------------------------------------------
if (lineNo != null) {
  const gi = lineNo - 1;
  if (gi < 0 || gi >= decoded.length) {
    process.stderr.write(`css-source: line ${lineNo} out of range (1..${decoded.length})\n`);
    process.exit(1);
  }
  const segs = decoded[gi].filter((s) => s.src != null);
  const result = {
    cssFile,
    cssLine: lineNo,
    mappings: segs.map((s) => ({
      source: srcLabel(s.src),
      sourceLine: s.origLine + 1,
      sourceColumn: s.origCol + 1,
      snippet: snippetFor(s.src, s.origLine),
    })),
  };
  if (asJson) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");
  } else {
    process.stdout.write(`${path.relative(process.cwd(), cssFile) || cssFile}:${lineNo}\n`);
    if (!segs.length) {
      process.stdout.write("  (no source-mapping segment for this generated line)\n");
    }
    for (const m of result.mappings) {
      process.stdout.write(`  → ${m.source}:${m.sourceLine}:${m.sourceColumn}\n`);
      if (m.snippet) process.stdout.write(`      | ${m.snippet}\n`);
    }
  }
  process.exit(0);
}

// --- mode: per-source summary ----------------------------------------------
const counts = new Map(); // srcIdx -> { genLines, samples: [{cssLine, origLine, origCol, snippet}] }
decoded.forEach((segs, gi) => {
  const hit = segs.find((s) => s.src != null);
  if (!hit) return;
  if (!counts.has(hit.src)) counts.set(hit.src, { genLines: 0, samples: [] });
  const rec = counts.get(hit.src);
  rec.genLines++;
  if (rec.samples.length < 4) {
    rec.samples.push({
      cssLine: gi + 1,
      origLine: hit.origLine + 1,
      origCol: hit.origCol + 1,
      snippet: snippetFor(hit.src, hit.origLine),
    });
  }
});

const totalGen = decoded.length;
const ranked = [...counts.entries()]
  .map(([idx, rec]) => ({
    source: srcLabel(idx),
    sourceIndex: idx,
    genLines: rec.genLines,
    percent: totalGen ? Math.round((rec.genLines / totalGen) * 1000) / 10 : 0,
    samples: rec.samples,
  }))
  .sort((a, b) => b.genLines - a.genLines);

const result = {
  cssFile,
  sourceMap: origin,
  generatedLines: totalGen,
  mappedSources: ranked.length,
  sources: ranked.slice(0, topN),
};

if (asJson) {
  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
} else {
  process.stdout.write(`${path.relative(process.cwd(), cssFile) || cssFile}\n`);
  process.stdout.write(`source map: ${origin}\n`);
  process.stdout.write(`generated lines: ${totalGen}  |  mapped SCSS sources: ${ranked.length}\n`);
  process.stdout.write("provenance (top sources by generated-line count):\n");
  if (!ranked.length) {
    process.stdout.write("  (no mapped segments)\n");
  }
  for (const r of ranked.slice(0, topN)) {
    process.stdout.write(`  ${String(r.percent).padStart(5)}%  ${String(r.genLines).padStart(5)} lines  ${r.source}\n`);
    for (const s of r.samples) {
      process.stdout.write(`        css:${s.cssLine} → scss:${s.origLine}:${s.origCol}  | ${s.snippet}\n`);
    }
  }
}
