#!/usr/bin/env bash
# check-scenarios-no-hardcoded-data.sh
#
# CI 强校验脚本：扫描所有 YAML 剧本，匹配硬编码数据模式。
# 发现任何匹配 → 退出码非零（阻断 CI）。
#
# 用法：
#   ./scripts/check-scenarios-no-hardcoded-data.sh [dir]
#
# 默认扫描 internal/server/mock_scenarios/
#
# 在 pre-commit hook + CI 流水线中调用。
set -euo pipefail

SCENARIOS_DIR="${1:-internal/server/mock_scenarios}"
ERRORS=0

if [ ! -d "$SCENARIOS_DIR" ]; then
  echo "⚠️  Scenarios directory not found: $SCENARIOS_DIR"
  echo "   (This is OK if T4 migration hasn't started yet)"
  exit 0
fi

# Find all YAML files
YAML_FILES=$(find "$SCENARIOS_DIR" -name '*.yaml' -o -name '*.yml' | sort)

if [ -z "$YAML_FILES" ]; then
  echo "ℹ️  No YAML files found in $SCENARIOS_DIR"
  exit 0
fi

FILE_COUNT=$(echo "$YAML_FILES" | wc -l)
echo "🔍 Scanning $FILE_COUNT YAML scenario files in $SCENARIOS_DIR ..."
echo ""

# Pattern 1: tool_result event (FORBIDDEN in YAML)
if echo "$YAML_FILES" | xargs grep -n '^\s*type:\s*tool_result' 2>/dev/null; then
  echo "❌ FORBIDDEN: 'type: tool_result' found in YAML (tool_result is auto-generated by MockEngine)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 2: Hardcoded paths (dir/dir/file.ext)
if echo "$YAML_FILES" | xargs grep -nE '[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\.(mp4|mkv|avi|mov|flv|webm|ts|m4v|wmv|json|log|txt|bin)' 2>/dev/null | \
   grep -vE '^\s*#' | grep -v 'mount_id:' | grep -v 'rel_path:' | grep -v 'SCHEMA.md' | grep -v 'EXAMPLE_' | grep -v 'source_glob:'; then
  echo "❌ FORBIDDEN: Hardcoded file paths found (paths must come from real tool results)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 3: Hardcoded file sizes (number + unit)
if echo "$YAML_FILES" | xargs grep -nE '[0-9]+\s*(MB|KB|GB|TB|bytes?)' 2>/dev/null | \
   grep -vE '^\s*#' | grep -v 'min_size:' | grep -v 'max_bytes:' | grep -v 'SCHEMA.md' | grep -v 'EXAMPLE_'; then
  echo "❌ FORBIDDEN: Hardcoded file sizes found (sizes must come from real tool results)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 4: Hardcoded counts (Chinese: "N 个文件/匹配/结果")
if echo "$YAML_FILES" | xargs grep -nE '[0-9]+\s*个(文件|匹配|结果|条目|记录|项|子目录|目录)' 2>/dev/null | \
   grep -vE '^\s*#' | grep -v 'SCHEMA.md' | grep -v 'EXAMPLE_'; then
  echo "❌ FORBIDDEN: Hardcoded counts found (counts must come from real tool results)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 5: Hardcoded error text
if echo "$YAML_FILES" | xargs grep -nE '(ERROR|失败|错误)[:：]\s*\S+' 2>/dev/null | \
   grep -vE '^\s*#' | grep -v 'SCHEMA.md' | grep -v 'EXAMPLE_'; then
  echo "❌ FORBIDDEN: Hardcoded error messages found (errors must come from real tool failures)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 6: Template syntax {{ or {%
if echo "$YAML_FILES" | xargs grep -nE '\{\{|\{%' 2>/dev/null | \
   grep -vE '^\s*#' | grep -v 'SCHEMA.md' | grep -v 'EXAMPLE_' | grep -v 'source_glob:' | grep -v 'pattern:'; then
  echo "❌ FORBIDDEN: Template syntax found (scenarios must use static text)"
  ERRORS=$((ERRORS + 1))
fi

# Pattern 7: user_text / free-form input fields in event data (not in presets)
# This is harder to check with grep alone; the Go validator handles this properly.
# Here we just check for user_text in non-preset contexts.

echo ""
if [ $ERRORS -gt 0 ]; then
  echo "💥 FAILED: Found $ERRORS violation(s). Fix the YAML files and re-run."
  exit 1
else
  echo "✅ PASSED: All $FILE_COUNT scenario files are clean."
  exit 0
fi
