//go:build objectbox

// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package objectbox

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type taskEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var TaskEntityBinding = taskEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 3872424929271192139,
}

// TaskEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var TaskEntity_ = struct {
	Id                 *objectbox.PropertyUint64
	TaskID             *objectbox.PropertyString
	Type               *objectbox.PropertyString
	Status             *objectbox.PropertyString
	ServiceName        *objectbox.PropertyString
	MethodName         *objectbox.PropertyString
	TenantID           *objectbox.PropertyString
	TriggeredBy        *objectbox.PropertyString
	RunID              *objectbox.PropertyString
	SourcePath         *objectbox.PropertyString
	TargetPath         *objectbox.PropertyString
	OutputPath         *objectbox.PropertyString
	PluginName         *objectbox.PropertyString
	Progress           *objectbox.PropertyInt
	Phase              *objectbox.PropertyString
	Error              *objectbox.PropertyString
	ErrorDetail        *objectbox.PropertyString
	Warning            *objectbox.PropertyString
	WarningDetail      *objectbox.PropertyString
	ContainerVersion   *objectbox.PropertyInt
	CipherMode         *objectbox.PropertyInt
	CompressionMode    *objectbox.PropertyString
	ExtraFields        *objectbox.PropertyString
	Steps              *objectbox.PropertyString
	MountID            *objectbox.PropertyString
	MountSubPath       *objectbox.PropertyString
	TargetMountID      *objectbox.PropertyString
	TargetMountSubPath *objectbox.PropertyString
	Password           *objectbox.PropertyString
	SecondaryPassword  *objectbox.PropertyString
	DurationMs         *objectbox.PropertyInt64
	InputJSON          *objectbox.PropertyString
	OutputJSON         *objectbox.PropertyString
	Attempts           *objectbox.PropertyInt
	Priority           *objectbox.PropertyInt
	TagsJSON           *objectbox.PropertyString
	CreatedAt          *objectbox.PropertyInt64
	CompletedAt        *objectbox.PropertyInt64
	RollbackOf         *objectbox.PropertyString
	OriginalPath       *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Type: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Status: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	ServiceName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	MethodName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TenantID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TriggeredBy: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	RunID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	SourcePath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TargetPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	OutputPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	PluginName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Progress: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Phase: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Error: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	ErrorDetail: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Warning: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     18,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	WarningDetail: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     19,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	ContainerVersion: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     20,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	CipherMode: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     21,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	CompressionMode: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     22,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	ExtraFields: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     23,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Steps: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     24,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	MountID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     25,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	MountSubPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     26,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TargetMountID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     27,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TargetMountSubPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     28,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Password: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     29,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	SecondaryPassword: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     30,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	DurationMs: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     31,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	InputJSON: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     32,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	OutputJSON: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     33,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Attempts: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     34,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	Priority: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     35,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	TagsJSON: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     36,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     37,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	CompletedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     38,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	RollbackOf: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     39,
			Entity: &TaskEntityBinding.Entity,
		},
	},
	OriginalPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     40,
			Entity: &TaskEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (taskEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (taskEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("TaskEntity", 1, 3872424929271192139)
	model.Property("Id", 6, 1, 6356774954063249018)
	model.PropertyFlags(1)
	model.Property("TaskID", 9, 2, 7782672555938078943)
	model.PropertyFlags(2080)
	model.PropertyIndex(1, 7288931818110734776)
	model.Property("Type", 9, 3, 4196086546543272800)
	model.PropertyFlags(2048)
	model.PropertyIndex(2, 2156776453276150285)
	model.Property("Status", 9, 4, 933472216561257892)
	model.PropertyFlags(2048)
	model.PropertyIndex(3, 1473501042027205721)
	model.Property("ServiceName", 9, 5, 3484493931947194807)
	model.PropertyFlags(2048)
	model.PropertyIndex(4, 6225769746588797307)
	model.Property("MethodName", 9, 6, 9106938143946264532)
	model.Property("TenantID", 9, 7, 7465114826411893203)
	model.PropertyFlags(2048)
	model.PropertyIndex(5, 4329779724931812305)
	model.Property("TriggeredBy", 9, 8, 1433004948313476956)
	model.PropertyFlags(2048)
	model.PropertyIndex(6, 8841522549793960955)
	model.Property("RunID", 9, 9, 1281365753301381027)
	model.PropertyFlags(2048)
	model.PropertyIndex(7, 5902307568500261331)
	model.Property("SourcePath", 9, 10, 7727372032310844269)
	model.Property("TargetPath", 9, 11, 4833882453150190830)
	model.Property("OutputPath", 9, 12, 5511193677958308079)
	model.Property("PluginName", 9, 13, 8500546850499555832)
	model.Property("Progress", 6, 14, 2588419120235336682)
	model.Property("Phase", 9, 15, 4735891242203566472)
	model.Property("Error", 9, 16, 7806430845164012537)
	model.Property("ErrorDetail", 9, 17, 3959366264539708150)
	model.Property("Warning", 9, 18, 2770800395604205615)
	model.Property("WarningDetail", 9, 19, 3846086568100666795)
	model.Property("ContainerVersion", 6, 20, 31103192969301327)
	model.Property("CipherMode", 6, 21, 2980545116198229546)
	model.Property("CompressionMode", 9, 22, 3439897940379117835)
	model.Property("ExtraFields", 9, 23, 4335356112774501400)
	model.Property("Steps", 9, 24, 7695923046418929121)
	model.Property("MountID", 9, 25, 9155186803592324401)
	model.Property("MountSubPath", 9, 26, 8957803834348069074)
	model.Property("TargetMountID", 9, 27, 6227634391272163949)
	model.Property("TargetMountSubPath", 9, 28, 4527076409012129884)
	model.Property("Password", 9, 29, 6635233644248406630)
	model.Property("SecondaryPassword", 9, 30, 5856414071571624129)
	model.Property("DurationMs", 6, 31, 8801909662171453388)
	model.Property("InputJSON", 9, 32, 226385159758727035)
	model.Property("OutputJSON", 9, 33, 1101285261197770158)
	model.Property("Attempts", 6, 34, 3550905774183277267)
	model.Property("Priority", 6, 35, 2594379740903007324)
	model.Property("TagsJSON", 9, 36, 8618734516176708981)
	model.Property("CreatedAt", 6, 37, 6415792073686850356)
	model.Property("CompletedAt", 6, 38, 5610687314652308119)
	model.Property("RollbackOf", 9, 39, 5108582749272267198)
	model.Property("OriginalPath", 9, 40, 740773247956381701)
	model.EntityLastPropertyId(40, 740773247956381701)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (taskEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*TaskEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (taskEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*TaskEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (taskEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (taskEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*TaskEntity)
	var offsetTaskID = fbutils.CreateStringOffset(fbb, obj.TaskID)
	var offsetType = fbutils.CreateStringOffset(fbb, obj.Type)
	var offsetStatus = fbutils.CreateStringOffset(fbb, obj.Status)
	var offsetServiceName = fbutils.CreateStringOffset(fbb, obj.ServiceName)
	var offsetMethodName = fbutils.CreateStringOffset(fbb, obj.MethodName)
	var offsetTenantID = fbutils.CreateStringOffset(fbb, obj.TenantID)
	var offsetTriggeredBy = fbutils.CreateStringOffset(fbb, obj.TriggeredBy)
	var offsetRunID = fbutils.CreateStringOffset(fbb, obj.RunID)
	var offsetSourcePath = fbutils.CreateStringOffset(fbb, obj.SourcePath)
	var offsetTargetPath = fbutils.CreateStringOffset(fbb, obj.TargetPath)
	var offsetOutputPath = fbutils.CreateStringOffset(fbb, obj.OutputPath)
	var offsetPluginName = fbutils.CreateStringOffset(fbb, obj.PluginName)
	var offsetPhase = fbutils.CreateStringOffset(fbb, obj.Phase)
	var offsetError = fbutils.CreateStringOffset(fbb, obj.Error)
	var offsetErrorDetail = fbutils.CreateStringOffset(fbb, obj.ErrorDetail)
	var offsetWarning = fbutils.CreateStringOffset(fbb, obj.Warning)
	var offsetWarningDetail = fbutils.CreateStringOffset(fbb, obj.WarningDetail)
	var offsetCompressionMode = fbutils.CreateStringOffset(fbb, obj.CompressionMode)
	var offsetExtraFields = fbutils.CreateStringOffset(fbb, obj.ExtraFields)
	var offsetSteps = fbutils.CreateStringOffset(fbb, obj.Steps)
	var offsetMountID = fbutils.CreateStringOffset(fbb, obj.MountID)
	var offsetMountSubPath = fbutils.CreateStringOffset(fbb, obj.MountSubPath)
	var offsetTargetMountID = fbutils.CreateStringOffset(fbb, obj.TargetMountID)
	var offsetTargetMountSubPath = fbutils.CreateStringOffset(fbb, obj.TargetMountSubPath)
	var offsetPassword = fbutils.CreateStringOffset(fbb, obj.Password)
	var offsetSecondaryPassword = fbutils.CreateStringOffset(fbb, obj.SecondaryPassword)
	var offsetInputJSON = fbutils.CreateStringOffset(fbb, obj.InputJSON)
	var offsetOutputJSON = fbutils.CreateStringOffset(fbb, obj.OutputJSON)
	var offsetTagsJSON = fbutils.CreateStringOffset(fbb, obj.TagsJSON)
	var offsetRollbackOf = fbutils.CreateStringOffset(fbb, obj.RollbackOf)
	var offsetOriginalPath = fbutils.CreateStringOffset(fbb, obj.OriginalPath)

	// build the FlatBuffers object
	fbb.StartObject(40)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTaskID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetType)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetStatus)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetServiceName)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetMethodName)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetTenantID)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetTriggeredBy)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetRunID)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetSourcePath)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetTargetPath)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetOutputPath)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetPluginName)
	fbutils.SetInt64Slot(fbb, 13, int64(obj.Progress))
	fbutils.SetUOffsetTSlot(fbb, 14, offsetPhase)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetError)
	fbutils.SetUOffsetTSlot(fbb, 16, offsetErrorDetail)
	fbutils.SetUOffsetTSlot(fbb, 17, offsetWarning)
	fbutils.SetUOffsetTSlot(fbb, 18, offsetWarningDetail)
	fbutils.SetInt64Slot(fbb, 19, int64(obj.ContainerVersion))
	fbutils.SetInt64Slot(fbb, 20, int64(obj.CipherMode))
	fbutils.SetUOffsetTSlot(fbb, 21, offsetCompressionMode)
	fbutils.SetUOffsetTSlot(fbb, 22, offsetExtraFields)
	fbutils.SetUOffsetTSlot(fbb, 23, offsetSteps)
	fbutils.SetUOffsetTSlot(fbb, 24, offsetMountID)
	fbutils.SetUOffsetTSlot(fbb, 25, offsetMountSubPath)
	fbutils.SetUOffsetTSlot(fbb, 26, offsetTargetMountID)
	fbutils.SetUOffsetTSlot(fbb, 27, offsetTargetMountSubPath)
	fbutils.SetUOffsetTSlot(fbb, 28, offsetPassword)
	fbutils.SetUOffsetTSlot(fbb, 29, offsetSecondaryPassword)
	fbutils.SetInt64Slot(fbb, 30, obj.DurationMs)
	fbutils.SetUOffsetTSlot(fbb, 31, offsetInputJSON)
	fbutils.SetUOffsetTSlot(fbb, 32, offsetOutputJSON)
	fbutils.SetInt64Slot(fbb, 33, int64(obj.Attempts))
	fbutils.SetInt64Slot(fbb, 34, int64(obj.Priority))
	fbutils.SetUOffsetTSlot(fbb, 35, offsetTagsJSON)
	fbutils.SetInt64Slot(fbb, 36, obj.CreatedAt)
	fbutils.SetInt64Slot(fbb, 37, obj.CompletedAt)
	fbutils.SetUOffsetTSlot(fbb, 38, offsetRollbackOf)
	fbutils.SetUOffsetTSlot(fbb, 39, offsetOriginalPath)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (taskEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'TaskEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &TaskEntity{
		Id:                 propId,
		TaskID:             fbutils.GetStringSlot(table, 6),
		Type:               fbutils.GetStringSlot(table, 8),
		Status:             fbutils.GetStringSlot(table, 10),
		ServiceName:        fbutils.GetStringSlot(table, 12),
		MethodName:         fbutils.GetStringSlot(table, 14),
		TenantID:           fbutils.GetStringSlot(table, 16),
		TriggeredBy:        fbutils.GetStringSlot(table, 18),
		RunID:              fbutils.GetStringSlot(table, 20),
		SourcePath:         fbutils.GetStringSlot(table, 22),
		TargetPath:         fbutils.GetStringSlot(table, 24),
		OutputPath:         fbutils.GetStringSlot(table, 26),
		PluginName:         fbutils.GetStringSlot(table, 28),
		Progress:           fbutils.GetIntSlot(table, 30),
		Phase:              fbutils.GetStringSlot(table, 32),
		Error:              fbutils.GetStringSlot(table, 34),
		ErrorDetail:        fbutils.GetStringSlot(table, 36),
		Warning:            fbutils.GetStringSlot(table, 38),
		WarningDetail:      fbutils.GetStringSlot(table, 40),
		ContainerVersion:   fbutils.GetIntSlot(table, 42),
		CipherMode:         fbutils.GetIntSlot(table, 44),
		CompressionMode:    fbutils.GetStringSlot(table, 46),
		ExtraFields:        fbutils.GetStringSlot(table, 48),
		Steps:              fbutils.GetStringSlot(table, 50),
		MountID:            fbutils.GetStringSlot(table, 52),
		MountSubPath:       fbutils.GetStringSlot(table, 54),
		TargetMountID:      fbutils.GetStringSlot(table, 56),
		TargetMountSubPath: fbutils.GetStringSlot(table, 58),
		Password:           fbutils.GetStringSlot(table, 60),
		SecondaryPassword:  fbutils.GetStringSlot(table, 62),
		DurationMs:         fbutils.GetInt64Slot(table, 64),
		InputJSON:          fbutils.GetStringSlot(table, 66),
		OutputJSON:         fbutils.GetStringSlot(table, 68),
		Attempts:           fbutils.GetIntSlot(table, 70),
		Priority:           fbutils.GetIntSlot(table, 72),
		TagsJSON:           fbutils.GetStringSlot(table, 74),
		CreatedAt:          fbutils.GetInt64Slot(table, 76),
		CompletedAt:        fbutils.GetInt64Slot(table, 78),
		RollbackOf:         fbutils.GetStringSlot(table, 80),
		OriginalPath:       fbutils.GetStringSlot(table, 82),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (taskEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*TaskEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (taskEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*TaskEntity), nil)
	}
	return append(slice.([]*TaskEntity), object.(*TaskEntity))
}

// Box provides CRUD access to TaskEntity objects
type TaskEntityBox struct {
	*objectbox.Box
}

// BoxForTaskEntity opens a box of TaskEntity objects
func BoxForTaskEntity(ob *objectbox.ObjectBox) *TaskEntityBox {
	return &TaskEntityBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the TaskEntity.Id property on the passed object will be assigned the new ID as well.
func (box *TaskEntityBox) Put(object *TaskEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the TaskEntity.Id property on the passed object will be assigned the new ID as well.
func (box *TaskEntityBox) Insert(object *TaskEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *TaskEntityBox) Update(object *TaskEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *TaskEntityBox) PutAsync(object *TaskEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the TaskEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the TaskEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *TaskEntityBox) PutMany(objects []*TaskEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *TaskEntityBox) Get(id uint64) (*TaskEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*TaskEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *TaskEntityBox) GetMany(ids ...uint64) ([]*TaskEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*TaskEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *TaskEntityBox) GetManyExisting(ids ...uint64) ([]*TaskEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*TaskEntity), nil
}

// GetAll reads all stored objects
func (box *TaskEntityBox) GetAll() ([]*TaskEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*TaskEntity), nil
}

// Remove deletes a single object
func (box *TaskEntityBox) Remove(object *TaskEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *TaskEntityBox) RemoveMany(objects ...*TaskEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the TaskEntity_ struct to create conditions.
// Keep the *TaskEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *TaskEntityBox) Query(conditions ...objectbox.Condition) *TaskEntityQuery {
	return &TaskEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the TaskEntity_ struct to create conditions.
// Keep the *TaskEntityQuery if you intend to execute the query multiple times.
func (box *TaskEntityBox) QueryOrError(conditions ...objectbox.Condition) (*TaskEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &TaskEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See TaskEntityAsyncBox for more information.
func (box *TaskEntityBox) Async() *TaskEntityAsyncBox {
	return &TaskEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// TaskEntityAsyncBox provides asynchronous operations on TaskEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type TaskEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForTaskEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use TaskEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForTaskEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *TaskEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &TaskEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *TaskEntityAsyncBox) Put(object *TaskEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *TaskEntityAsyncBox) Insert(object *TaskEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *TaskEntityAsyncBox) Update(object *TaskEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *TaskEntityAsyncBox) Remove(object *TaskEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all TaskEntity which Id is either 42 or 47:
//
// box.Query(TaskEntity_.Id.In(42, 47)).Find()
type TaskEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *TaskEntityQuery) Find() ([]*TaskEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*TaskEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *TaskEntityQuery) Offset(offset uint64) *TaskEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *TaskEntityQuery) Limit(limit uint64) *TaskEntityQuery {
	query.Query.Limit(limit)
	return query
}

type snapshotEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var SnapshotEntityBinding = snapshotEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 4101703234515892546,
}

// SnapshotEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var SnapshotEntity_ = struct {
	Id           *objectbox.PropertyUint64
	TaskID       *objectbox.PropertyString
	SnapshotType *objectbox.PropertyString
	Data         *objectbox.PropertyByteVector
	CreatedAt    *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &SnapshotEntityBinding.Entity,
		},
	},
	TaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &SnapshotEntityBinding.Entity,
		},
	},
	SnapshotType: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &SnapshotEntityBinding.Entity,
		},
	},
	Data: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &SnapshotEntityBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &SnapshotEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (snapshotEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (snapshotEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("SnapshotEntity", 2, 4101703234515892546)
	model.Property("Id", 6, 1, 4552075918254647397)
	model.PropertyFlags(1)
	model.Property("TaskID", 9, 2, 325826554806887577)
	model.PropertyFlags(2048)
	model.PropertyIndex(8, 3984301413854355923)
	model.Property("SnapshotType", 9, 3, 578890115553415874)
	model.Property("Data", 23, 4, 1367550697488280667)
	model.Property("CreatedAt", 6, 5, 4789039437043571342)
	model.EntityLastPropertyId(5, 4789039437043571342)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (snapshotEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*SnapshotEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (snapshotEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*SnapshotEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (snapshotEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (snapshotEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*SnapshotEntity)
	var offsetTaskID = fbutils.CreateStringOffset(fbb, obj.TaskID)
	var offsetSnapshotType = fbutils.CreateStringOffset(fbb, obj.SnapshotType)
	var offsetData = fbutils.CreateByteVectorOffset(fbb, obj.Data)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTaskID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetSnapshotType)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetData)
	fbutils.SetInt64Slot(fbb, 4, obj.CreatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (snapshotEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'SnapshotEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &SnapshotEntity{
		Id:           propId,
		TaskID:       fbutils.GetStringSlot(table, 6),
		SnapshotType: fbutils.GetStringSlot(table, 8),
		Data:         fbutils.GetByteVectorSlot(table, 10),
		CreatedAt:    fbutils.GetInt64Slot(table, 12),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (snapshotEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*SnapshotEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (snapshotEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*SnapshotEntity), nil)
	}
	return append(slice.([]*SnapshotEntity), object.(*SnapshotEntity))
}

// Box provides CRUD access to SnapshotEntity objects
type SnapshotEntityBox struct {
	*objectbox.Box
}

// BoxForSnapshotEntity opens a box of SnapshotEntity objects
func BoxForSnapshotEntity(ob *objectbox.ObjectBox) *SnapshotEntityBox {
	return &SnapshotEntityBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the SnapshotEntity.Id property on the passed object will be assigned the new ID as well.
func (box *SnapshotEntityBox) Put(object *SnapshotEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the SnapshotEntity.Id property on the passed object will be assigned the new ID as well.
func (box *SnapshotEntityBox) Insert(object *SnapshotEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *SnapshotEntityBox) Update(object *SnapshotEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *SnapshotEntityBox) PutAsync(object *SnapshotEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the SnapshotEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the SnapshotEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *SnapshotEntityBox) PutMany(objects []*SnapshotEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *SnapshotEntityBox) Get(id uint64) (*SnapshotEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*SnapshotEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *SnapshotEntityBox) GetMany(ids ...uint64) ([]*SnapshotEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*SnapshotEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *SnapshotEntityBox) GetManyExisting(ids ...uint64) ([]*SnapshotEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*SnapshotEntity), nil
}

// GetAll reads all stored objects
func (box *SnapshotEntityBox) GetAll() ([]*SnapshotEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*SnapshotEntity), nil
}

// Remove deletes a single object
func (box *SnapshotEntityBox) Remove(object *SnapshotEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *SnapshotEntityBox) RemoveMany(objects ...*SnapshotEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the SnapshotEntity_ struct to create conditions.
// Keep the *SnapshotEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *SnapshotEntityBox) Query(conditions ...objectbox.Condition) *SnapshotEntityQuery {
	return &SnapshotEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the SnapshotEntity_ struct to create conditions.
// Keep the *SnapshotEntityQuery if you intend to execute the query multiple times.
func (box *SnapshotEntityBox) QueryOrError(conditions ...objectbox.Condition) (*SnapshotEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &SnapshotEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See SnapshotEntityAsyncBox for more information.
func (box *SnapshotEntityBox) Async() *SnapshotEntityAsyncBox {
	return &SnapshotEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// SnapshotEntityAsyncBox provides asynchronous operations on SnapshotEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type SnapshotEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForSnapshotEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use SnapshotEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForSnapshotEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *SnapshotEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &SnapshotEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *SnapshotEntityAsyncBox) Put(object *SnapshotEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *SnapshotEntityAsyncBox) Insert(object *SnapshotEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *SnapshotEntityAsyncBox) Update(object *SnapshotEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *SnapshotEntityAsyncBox) Remove(object *SnapshotEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all SnapshotEntity which Id is either 42 or 47:
//
// box.Query(SnapshotEntity_.Id.In(42, 47)).Find()
type SnapshotEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *SnapshotEntityQuery) Find() ([]*SnapshotEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*SnapshotEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *SnapshotEntityQuery) Offset(offset uint64) *SnapshotEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *SnapshotEntityQuery) Limit(limit uint64) *SnapshotEntityQuery {
	query.Query.Limit(limit)
	return query
}

type trashEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var TrashEntityBinding = trashEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 3922460418110320008,
}

// TrashEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var TrashEntity_ = struct {
	Id            *objectbox.PropertyUint64
	TrashID       *objectbox.PropertyString
	OriginalPath  *objectbox.PropertyString
	TrashPath     *objectbox.PropertyString
	IsDirectory   *objectbox.PropertyBool
	Size          *objectbox.PropertyInt64
	DeletedAt     *objectbox.PropertyInt64
	TaskID        *objectbox.PropertyString
	RestoreTaskID *objectbox.PropertyString
	Metadata      *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	TrashID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	OriginalPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	TrashPath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	IsDirectory: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	Size: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	DeletedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	TaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	RestoreTaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &TrashEntityBinding.Entity,
		},
	},
	Metadata: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &TrashEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (trashEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (trashEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("TrashEntity", 3, 3922460418110320008)
	model.Property("Id", 6, 1, 4433775962367837885)
	model.PropertyFlags(1)
	model.Property("TrashID", 9, 2, 1199237736179682193)
	model.PropertyFlags(2080)
	model.PropertyIndex(9, 8390895468056829695)
	model.Property("OriginalPath", 9, 3, 5263088786399774760)
	model.Property("TrashPath", 9, 4, 3558552140035052876)
	model.Property("IsDirectory", 1, 5, 6556432139543300165)
	model.Property("Size", 6, 6, 8201979443432824967)
	model.Property("DeletedAt", 6, 7, 2732412092154596195)
	model.Property("TaskID", 9, 8, 4918017697601404189)
	model.PropertyFlags(2048)
	model.PropertyIndex(10, 7694352498625880187)
	model.Property("RestoreTaskID", 9, 9, 6283088300805847177)
	model.Property("Metadata", 9, 10, 7559313960195856527)
	model.EntityLastPropertyId(10, 7559313960195856527)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (trashEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*TrashEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (trashEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*TrashEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (trashEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (trashEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*TrashEntity)
	var offsetTrashID = fbutils.CreateStringOffset(fbb, obj.TrashID)
	var offsetOriginalPath = fbutils.CreateStringOffset(fbb, obj.OriginalPath)
	var offsetTrashPath = fbutils.CreateStringOffset(fbb, obj.TrashPath)
	var offsetTaskID = fbutils.CreateStringOffset(fbb, obj.TaskID)
	var offsetRestoreTaskID = fbutils.CreateStringOffset(fbb, obj.RestoreTaskID)
	var offsetMetadata = fbutils.CreateStringOffset(fbb, obj.Metadata)

	// build the FlatBuffers object
	fbb.StartObject(10)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTrashID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetOriginalPath)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetTrashPath)
	fbutils.SetBoolSlot(fbb, 4, obj.IsDirectory)
	fbutils.SetInt64Slot(fbb, 5, obj.Size)
	fbutils.SetInt64Slot(fbb, 6, obj.DeletedAt)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetTaskID)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetRestoreTaskID)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetMetadata)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (trashEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'TrashEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &TrashEntity{
		Id:            propId,
		TrashID:       fbutils.GetStringSlot(table, 6),
		OriginalPath:  fbutils.GetStringSlot(table, 8),
		TrashPath:     fbutils.GetStringSlot(table, 10),
		IsDirectory:   fbutils.GetBoolSlot(table, 12),
		Size:          fbutils.GetInt64Slot(table, 14),
		DeletedAt:     fbutils.GetInt64Slot(table, 16),
		TaskID:        fbutils.GetStringSlot(table, 18),
		RestoreTaskID: fbutils.GetStringSlot(table, 20),
		Metadata:      fbutils.GetStringSlot(table, 22),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (trashEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*TrashEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (trashEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*TrashEntity), nil)
	}
	return append(slice.([]*TrashEntity), object.(*TrashEntity))
}

// Box provides CRUD access to TrashEntity objects
type TrashEntityBox struct {
	*objectbox.Box
}

// BoxForTrashEntity opens a box of TrashEntity objects
func BoxForTrashEntity(ob *objectbox.ObjectBox) *TrashEntityBox {
	return &TrashEntityBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the TrashEntity.Id property on the passed object will be assigned the new ID as well.
func (box *TrashEntityBox) Put(object *TrashEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the TrashEntity.Id property on the passed object will be assigned the new ID as well.
func (box *TrashEntityBox) Insert(object *TrashEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *TrashEntityBox) Update(object *TrashEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *TrashEntityBox) PutAsync(object *TrashEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the TrashEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the TrashEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *TrashEntityBox) PutMany(objects []*TrashEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *TrashEntityBox) Get(id uint64) (*TrashEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*TrashEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *TrashEntityBox) GetMany(ids ...uint64) ([]*TrashEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*TrashEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *TrashEntityBox) GetManyExisting(ids ...uint64) ([]*TrashEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*TrashEntity), nil
}

// GetAll reads all stored objects
func (box *TrashEntityBox) GetAll() ([]*TrashEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*TrashEntity), nil
}

// Remove deletes a single object
func (box *TrashEntityBox) Remove(object *TrashEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *TrashEntityBox) RemoveMany(objects ...*TrashEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the TrashEntity_ struct to create conditions.
// Keep the *TrashEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *TrashEntityBox) Query(conditions ...objectbox.Condition) *TrashEntityQuery {
	return &TrashEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the TrashEntity_ struct to create conditions.
// Keep the *TrashEntityQuery if you intend to execute the query multiple times.
func (box *TrashEntityBox) QueryOrError(conditions ...objectbox.Condition) (*TrashEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &TrashEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See TrashEntityAsyncBox for more information.
func (box *TrashEntityBox) Async() *TrashEntityAsyncBox {
	return &TrashEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// TrashEntityAsyncBox provides asynchronous operations on TrashEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type TrashEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForTrashEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use TrashEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForTrashEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *TrashEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &TrashEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *TrashEntityAsyncBox) Put(object *TrashEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *TrashEntityAsyncBox) Insert(object *TrashEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *TrashEntityAsyncBox) Update(object *TrashEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *TrashEntityAsyncBox) Remove(object *TrashEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all TrashEntity which Id is either 42 or 47:
//
// box.Query(TrashEntity_.Id.In(42, 47)).Find()
type TrashEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *TrashEntityQuery) Find() ([]*TrashEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*TrashEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *TrashEntityQuery) Offset(offset uint64) *TrashEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *TrashEntityQuery) Limit(limit uint64) *TrashEntityQuery {
	query.Query.Limit(limit)
	return query
}

type performanceMetricsEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var PerformanceMetricsEntityBinding = performanceMetricsEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 4,
	},
	Uid: 6701245365849373038,
}

// PerformanceMetricsEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var PerformanceMetricsEntity_ = struct {
	Id               *objectbox.PropertyUint64
	TaskID           *objectbox.PropertyString
	TaskType         *objectbox.PropertyString
	PluginName       *objectbox.PropertyString
	ContainerVersion *objectbox.PropertyInt
	CipherMode       *objectbox.PropertyInt
	CompressionMode  *objectbox.PropertyString
	SourceSize       *objectbox.PropertyInt64
	OutputSize       *objectbox.PropertyInt64
	SizeRatio        *objectbox.PropertyFloat64
	AvgThroughput    *objectbox.PropertyFloat64
	PeakThroughput   *objectbox.PropertyFloat64
	P50Throughput    *objectbox.PropertyFloat64
	P99Throughput    *objectbox.PropertyFloat64
	TotalDurationMs  *objectbox.PropertyInt64
	PhaseTimingsJSON *objectbox.PropertyString
	Grade            *objectbox.PropertyString
	GradeScore       *objectbox.PropertyFloat64
	GradeReason      *objectbox.PropertyString
	CPUScore         *objectbox.PropertyFloat64
	CPULabel         *objectbox.PropertyString
	CreatedAt        *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	TaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	TaskType: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	PluginName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	ContainerVersion: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	CipherMode: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	CompressionMode: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	SourceSize: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	OutputSize: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	SizeRatio: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	AvgThroughput: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	PeakThroughput: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	P50Throughput: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	P99Throughput: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	TotalDurationMs: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	PhaseTimingsJSON: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	Grade: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	GradeScore: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     18,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	GradeReason: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     19,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	CPUScore: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     20,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	CPULabel: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     21,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     22,
			Entity: &PerformanceMetricsEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (performanceMetricsEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (performanceMetricsEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("PerformanceMetricsEntity", 4, 6701245365849373038)
	model.Property("Id", 6, 1, 3478443943288228331)
	model.PropertyFlags(1)
	model.Property("TaskID", 9, 2, 2582838948699545871)
	model.PropertyFlags(2080)
	model.PropertyIndex(11, 2942812111776427904)
	model.Property("TaskType", 9, 3, 844484565504130539)
	model.PropertyFlags(2048)
	model.PropertyIndex(12, 3786334623736522575)
	model.Property("PluginName", 9, 4, 356560710875604842)
	model.PropertyFlags(2048)
	model.PropertyIndex(13, 9034625844184433334)
	model.Property("ContainerVersion", 6, 5, 5920863055305217924)
	model.Property("CipherMode", 6, 6, 6345984456985952081)
	model.Property("CompressionMode", 9, 7, 6669900452949758945)
	model.Property("SourceSize", 6, 8, 4368730564403379573)
	model.Property("OutputSize", 6, 9, 3850003096240927383)
	model.Property("SizeRatio", 8, 10, 4871189218234678467)
	model.Property("AvgThroughput", 8, 11, 1438959083647762731)
	model.Property("PeakThroughput", 8, 12, 4054367023234514699)
	model.Property("P50Throughput", 8, 13, 7272538587778825212)
	model.Property("P99Throughput", 8, 14, 6719009594476137291)
	model.Property("TotalDurationMs", 6, 15, 4390926293987710302)
	model.Property("PhaseTimingsJSON", 9, 16, 5850218311428713298)
	model.Property("Grade", 9, 17, 3765767044010309736)
	model.Property("GradeScore", 8, 18, 2919910620581844374)
	model.Property("GradeReason", 9, 19, 4817663710232761664)
	model.Property("CPUScore", 8, 20, 2817260017100801783)
	model.Property("CPULabel", 9, 21, 3064202451484119303)
	model.Property("CreatedAt", 6, 22, 8637201032127292611)
	model.EntityLastPropertyId(22, 8637201032127292611)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (performanceMetricsEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*PerformanceMetricsEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (performanceMetricsEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*PerformanceMetricsEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (performanceMetricsEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (performanceMetricsEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*PerformanceMetricsEntity)
	var offsetTaskID = fbutils.CreateStringOffset(fbb, obj.TaskID)
	var offsetTaskType = fbutils.CreateStringOffset(fbb, obj.TaskType)
	var offsetPluginName = fbutils.CreateStringOffset(fbb, obj.PluginName)
	var offsetCompressionMode = fbutils.CreateStringOffset(fbb, obj.CompressionMode)
	var offsetPhaseTimingsJSON = fbutils.CreateStringOffset(fbb, obj.PhaseTimingsJSON)
	var offsetGrade = fbutils.CreateStringOffset(fbb, obj.Grade)
	var offsetGradeReason = fbutils.CreateStringOffset(fbb, obj.GradeReason)
	var offsetCPULabel = fbutils.CreateStringOffset(fbb, obj.CPULabel)

	// build the FlatBuffers object
	fbb.StartObject(22)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTaskID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetTaskType)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetPluginName)
	fbutils.SetInt64Slot(fbb, 4, int64(obj.ContainerVersion))
	fbutils.SetInt64Slot(fbb, 5, int64(obj.CipherMode))
	fbutils.SetUOffsetTSlot(fbb, 6, offsetCompressionMode)
	fbutils.SetInt64Slot(fbb, 7, obj.SourceSize)
	fbutils.SetInt64Slot(fbb, 8, obj.OutputSize)
	fbutils.SetFloat64Slot(fbb, 9, obj.SizeRatio)
	fbutils.SetFloat64Slot(fbb, 10, obj.AvgThroughput)
	fbutils.SetFloat64Slot(fbb, 11, obj.PeakThroughput)
	fbutils.SetFloat64Slot(fbb, 12, obj.P50Throughput)
	fbutils.SetFloat64Slot(fbb, 13, obj.P99Throughput)
	fbutils.SetInt64Slot(fbb, 14, obj.TotalDurationMs)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetPhaseTimingsJSON)
	fbutils.SetUOffsetTSlot(fbb, 16, offsetGrade)
	fbutils.SetFloat64Slot(fbb, 17, obj.GradeScore)
	fbutils.SetUOffsetTSlot(fbb, 18, offsetGradeReason)
	fbutils.SetFloat64Slot(fbb, 19, obj.CPUScore)
	fbutils.SetUOffsetTSlot(fbb, 20, offsetCPULabel)
	fbutils.SetInt64Slot(fbb, 21, obj.CreatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (performanceMetricsEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'PerformanceMetricsEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &PerformanceMetricsEntity{
		Id:               propId,
		TaskID:           fbutils.GetStringSlot(table, 6),
		TaskType:         fbutils.GetStringSlot(table, 8),
		PluginName:       fbutils.GetStringSlot(table, 10),
		ContainerVersion: fbutils.GetIntSlot(table, 12),
		CipherMode:       fbutils.GetIntSlot(table, 14),
		CompressionMode:  fbutils.GetStringSlot(table, 16),
		SourceSize:       fbutils.GetInt64Slot(table, 18),
		OutputSize:       fbutils.GetInt64Slot(table, 20),
		SizeRatio:        fbutils.GetFloat64Slot(table, 22),
		AvgThroughput:    fbutils.GetFloat64Slot(table, 24),
		PeakThroughput:   fbutils.GetFloat64Slot(table, 26),
		P50Throughput:    fbutils.GetFloat64Slot(table, 28),
		P99Throughput:    fbutils.GetFloat64Slot(table, 30),
		TotalDurationMs:  fbutils.GetInt64Slot(table, 32),
		PhaseTimingsJSON: fbutils.GetStringSlot(table, 34),
		Grade:            fbutils.GetStringSlot(table, 36),
		GradeScore:       fbutils.GetFloat64Slot(table, 38),
		GradeReason:      fbutils.GetStringSlot(table, 40),
		CPUScore:         fbutils.GetFloat64Slot(table, 42),
		CPULabel:         fbutils.GetStringSlot(table, 44),
		CreatedAt:        fbutils.GetInt64Slot(table, 46),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (performanceMetricsEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*PerformanceMetricsEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (performanceMetricsEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*PerformanceMetricsEntity), nil)
	}
	return append(slice.([]*PerformanceMetricsEntity), object.(*PerformanceMetricsEntity))
}

// Box provides CRUD access to PerformanceMetricsEntity objects
type PerformanceMetricsEntityBox struct {
	*objectbox.Box
}

// BoxForPerformanceMetricsEntity opens a box of PerformanceMetricsEntity objects
func BoxForPerformanceMetricsEntity(ob *objectbox.ObjectBox) *PerformanceMetricsEntityBox {
	return &PerformanceMetricsEntityBox{
		Box: ob.InternalBox(4),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the PerformanceMetricsEntity.Id property on the passed object will be assigned the new ID as well.
func (box *PerformanceMetricsEntityBox) Put(object *PerformanceMetricsEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the PerformanceMetricsEntity.Id property on the passed object will be assigned the new ID as well.
func (box *PerformanceMetricsEntityBox) Insert(object *PerformanceMetricsEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *PerformanceMetricsEntityBox) Update(object *PerformanceMetricsEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *PerformanceMetricsEntityBox) PutAsync(object *PerformanceMetricsEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the PerformanceMetricsEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the PerformanceMetricsEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *PerformanceMetricsEntityBox) PutMany(objects []*PerformanceMetricsEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *PerformanceMetricsEntityBox) Get(id uint64) (*PerformanceMetricsEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*PerformanceMetricsEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *PerformanceMetricsEntityBox) GetMany(ids ...uint64) ([]*PerformanceMetricsEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*PerformanceMetricsEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *PerformanceMetricsEntityBox) GetManyExisting(ids ...uint64) ([]*PerformanceMetricsEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*PerformanceMetricsEntity), nil
}

// GetAll reads all stored objects
func (box *PerformanceMetricsEntityBox) GetAll() ([]*PerformanceMetricsEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*PerformanceMetricsEntity), nil
}

// Remove deletes a single object
func (box *PerformanceMetricsEntityBox) Remove(object *PerformanceMetricsEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *PerformanceMetricsEntityBox) RemoveMany(objects ...*PerformanceMetricsEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the PerformanceMetricsEntity_ struct to create conditions.
// Keep the *PerformanceMetricsEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *PerformanceMetricsEntityBox) Query(conditions ...objectbox.Condition) *PerformanceMetricsEntityQuery {
	return &PerformanceMetricsEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the PerformanceMetricsEntity_ struct to create conditions.
// Keep the *PerformanceMetricsEntityQuery if you intend to execute the query multiple times.
func (box *PerformanceMetricsEntityBox) QueryOrError(conditions ...objectbox.Condition) (*PerformanceMetricsEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &PerformanceMetricsEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See PerformanceMetricsEntityAsyncBox for more information.
func (box *PerformanceMetricsEntityBox) Async() *PerformanceMetricsEntityAsyncBox {
	return &PerformanceMetricsEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// PerformanceMetricsEntityAsyncBox provides asynchronous operations on PerformanceMetricsEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type PerformanceMetricsEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForPerformanceMetricsEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use PerformanceMetricsEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForPerformanceMetricsEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *PerformanceMetricsEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 4, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 4: %s" + err.Error())
	}
	return &PerformanceMetricsEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *PerformanceMetricsEntityAsyncBox) Put(object *PerformanceMetricsEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *PerformanceMetricsEntityAsyncBox) Insert(object *PerformanceMetricsEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *PerformanceMetricsEntityAsyncBox) Update(object *PerformanceMetricsEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *PerformanceMetricsEntityAsyncBox) Remove(object *PerformanceMetricsEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all PerformanceMetricsEntity which Id is either 42 or 47:
//
// box.Query(PerformanceMetricsEntity_.Id.In(42, 47)).Find()
type PerformanceMetricsEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *PerformanceMetricsEntityQuery) Find() ([]*PerformanceMetricsEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*PerformanceMetricsEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *PerformanceMetricsEntityQuery) Offset(offset uint64) *PerformanceMetricsEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *PerformanceMetricsEntityQuery) Limit(limit uint64) *PerformanceMetricsEntityQuery {
	query.Query.Limit(limit)
	return query
}

type calibrationEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var CalibrationEntityBinding = calibrationEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 5,
	},
	Uid: 5288715128295696624,
}

// CalibrationEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var CalibrationEntity_ = struct {
	Id            *objectbox.PropertyUint64
	CPUScore      *objectbox.PropertyFloat64
	AESThroughput *objectbox.PropertyFloat64
	CPULabel      *objectbox.PropertyString
	CalibratedAt  *objectbox.PropertyInt64
	GoVersion     *objectbox.PropertyString
	OS            *objectbox.PropertyString
	Arch          *objectbox.PropertyString
	NumCPU        *objectbox.PropertyInt
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	CPUScore: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	AESThroughput: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	CPULabel: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	CalibratedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	GoVersion: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	OS: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	Arch: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
	NumCPU: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &CalibrationEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (calibrationEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (calibrationEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("CalibrationEntity", 5, 5288715128295696624)
	model.Property("Id", 6, 1, 7594416637098841766)
	model.PropertyFlags(1)
	model.Property("CPUScore", 8, 2, 5254556915900638771)
	model.Property("AESThroughput", 8, 3, 2800342198479135936)
	model.Property("CPULabel", 9, 4, 4689142423969570699)
	model.Property("CalibratedAt", 6, 5, 2581522366689497910)
	model.Property("GoVersion", 9, 6, 2848123836301742031)
	model.Property("OS", 9, 7, 1080424273025926597)
	model.Property("Arch", 9, 8, 5999572475397474896)
	model.Property("NumCPU", 6, 9, 593601434248276002)
	model.EntityLastPropertyId(9, 593601434248276002)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (calibrationEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*CalibrationEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (calibrationEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*CalibrationEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (calibrationEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (calibrationEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*CalibrationEntity)
	var offsetCPULabel = fbutils.CreateStringOffset(fbb, obj.CPULabel)
	var offsetGoVersion = fbutils.CreateStringOffset(fbb, obj.GoVersion)
	var offsetOS = fbutils.CreateStringOffset(fbb, obj.OS)
	var offsetArch = fbutils.CreateStringOffset(fbb, obj.Arch)

	// build the FlatBuffers object
	fbb.StartObject(9)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetFloat64Slot(fbb, 1, obj.CPUScore)
	fbutils.SetFloat64Slot(fbb, 2, obj.AESThroughput)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetCPULabel)
	fbutils.SetInt64Slot(fbb, 4, obj.CalibratedAt)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetGoVersion)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetOS)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetArch)
	fbutils.SetInt64Slot(fbb, 8, int64(obj.NumCPU))
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (calibrationEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'CalibrationEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &CalibrationEntity{
		Id:            propId,
		CPUScore:      fbutils.GetFloat64Slot(table, 6),
		AESThroughput: fbutils.GetFloat64Slot(table, 8),
		CPULabel:      fbutils.GetStringSlot(table, 10),
		CalibratedAt:  fbutils.GetInt64Slot(table, 12),
		GoVersion:     fbutils.GetStringSlot(table, 14),
		OS:            fbutils.GetStringSlot(table, 16),
		Arch:          fbutils.GetStringSlot(table, 18),
		NumCPU:        fbutils.GetIntSlot(table, 20),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (calibrationEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*CalibrationEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (calibrationEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*CalibrationEntity), nil)
	}
	return append(slice.([]*CalibrationEntity), object.(*CalibrationEntity))
}

// Box provides CRUD access to CalibrationEntity objects
type CalibrationEntityBox struct {
	*objectbox.Box
}

// BoxForCalibrationEntity opens a box of CalibrationEntity objects
func BoxForCalibrationEntity(ob *objectbox.ObjectBox) *CalibrationEntityBox {
	return &CalibrationEntityBox{
		Box: ob.InternalBox(5),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the CalibrationEntity.Id property on the passed object will be assigned the new ID as well.
func (box *CalibrationEntityBox) Put(object *CalibrationEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the CalibrationEntity.Id property on the passed object will be assigned the new ID as well.
func (box *CalibrationEntityBox) Insert(object *CalibrationEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *CalibrationEntityBox) Update(object *CalibrationEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *CalibrationEntityBox) PutAsync(object *CalibrationEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the CalibrationEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the CalibrationEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *CalibrationEntityBox) PutMany(objects []*CalibrationEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *CalibrationEntityBox) Get(id uint64) (*CalibrationEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*CalibrationEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *CalibrationEntityBox) GetMany(ids ...uint64) ([]*CalibrationEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*CalibrationEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *CalibrationEntityBox) GetManyExisting(ids ...uint64) ([]*CalibrationEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*CalibrationEntity), nil
}

// GetAll reads all stored objects
func (box *CalibrationEntityBox) GetAll() ([]*CalibrationEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*CalibrationEntity), nil
}

// Remove deletes a single object
func (box *CalibrationEntityBox) Remove(object *CalibrationEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *CalibrationEntityBox) RemoveMany(objects ...*CalibrationEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the CalibrationEntity_ struct to create conditions.
// Keep the *CalibrationEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *CalibrationEntityBox) Query(conditions ...objectbox.Condition) *CalibrationEntityQuery {
	return &CalibrationEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the CalibrationEntity_ struct to create conditions.
// Keep the *CalibrationEntityQuery if you intend to execute the query multiple times.
func (box *CalibrationEntityBox) QueryOrError(conditions ...objectbox.Condition) (*CalibrationEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &CalibrationEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See CalibrationEntityAsyncBox for more information.
func (box *CalibrationEntityBox) Async() *CalibrationEntityAsyncBox {
	return &CalibrationEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// CalibrationEntityAsyncBox provides asynchronous operations on CalibrationEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type CalibrationEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForCalibrationEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use CalibrationEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForCalibrationEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *CalibrationEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 5, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 5: %s" + err.Error())
	}
	return &CalibrationEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *CalibrationEntityAsyncBox) Put(object *CalibrationEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *CalibrationEntityAsyncBox) Insert(object *CalibrationEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *CalibrationEntityAsyncBox) Update(object *CalibrationEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *CalibrationEntityAsyncBox) Remove(object *CalibrationEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all CalibrationEntity which Id is either 42 or 47:
//
// box.Query(CalibrationEntity_.Id.In(42, 47)).Find()
type CalibrationEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *CalibrationEntityQuery) Find() ([]*CalibrationEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*CalibrationEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *CalibrationEntityQuery) Offset(offset uint64) *CalibrationEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *CalibrationEntityQuery) Limit(limit uint64) *CalibrationEntityQuery {
	query.Query.Limit(limit)
	return query
}
